name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build and test
        run: |
          rsync -av ./ /root/ros2_ws/src/mypkg
          cd /root/ros2_ws
          sudo rosdep update
          sudo rosdep install -i --from-path src --rosdistro humble -y
          sudo bash -xv ./src/mypkg/test/test.bash /root
